### ISSUE TITLE
Check and try to fix incorrect Object Number Start, in the 'xref' table.

### ISSUE THREAD

**Issue by Bennyz1** [katjas/PDFrenderer#27]
There are pdf files that wrongly using xref table that start from the value 1 instead of 0.
For example:
```
xref
1 7
0000000000 65535 f 
0000000009 00000 n 
0000512165 00000 n 
0000512262 00000 n 
0000512449 00000 n 
0000512507 00000 n 
0000512558 00000 n 
trailer
```
Therefore, we may try to "fix" this situation, by "consider" the Object ID as 0 (zero)
only in case the **first** Object data is:
```
0000000000 65535 f 
```

**Comment by Bennyz1** [comment]
Fix is done on "Bennyz1" brunch.

**Comment by katjas** [comment]
Thanks for the input, I merged the fix into my branch now.
Kind regards,
Katja
