### ISSUE TITLE
Problem printing àáâãäå

### ISSUE THREAD

**Issue by jeroenbreedveld** [katjas/PDFrenderer#30]
Hi,

I'm using this fork of pdf-renderer to solve some out-of-memory problems I had with the original source.

These problems were solved but I'm is still not capable of printing a certain pdf I have containing the characters àáâãäå. The result is that the characters are not printed and all other a's in the text are not printed as well.

Are you interested in investigating this problem? It would help me a great deal. I could not attach the pdf to this ticket...

Regards,

Jeroen

**Comment by katjas** [comment]
Hi Jeroen,
do you have the possibility to provide the sample PDF somewhere? Otherwise it'll be hard to analyse the problem.
Kind regards,
Katja

**Comment by jeroenbreedveld** [comment]
Hi Katja,

Thanks for your response, I attached the pdf in question.

I just tested it against pdfbox (1.8.9) and then the printing takes several
minutes but in the end it does print the pdf, I don't know exactly what
that means but it does tell the pdf itself is problematic.

If you can't reproduce the problem I can give you the code I'm using.

Again, thanks for your effort!




Met vriendelijke groet,

Jeroen Breedveld

**Comment by katjas** [comment]
Hi Jeroen,
sorry but there is no PDF attached, can you try again?
Thanks,
Katja

**Comment by jeroenbreedveld** [comment]
Hi Katja,

The pdf was attached, it's attached again. Could the mailinglist remove it?



Met vriendelijke groet,

Jeroen Breedveld

**Comment by jeroenbreedveld** [comment]
Hi Katja,

Did you receive the pdf? Did you find the problem?



Met vriendelijke groet,

Jeroen Breedveld

**Comment by katjas** [comment]
Hello Jeroen,

sorry but the PDF was again not attached.
Kind regards,
Katja

**Comment by jeroenbreedveld** [comment]
Hi Katja,

Do you have an alternative email adres for me? I could share it with you
using WeTransfer?



Met vriendelijke groet,

Jeroen Breedveld

**Comment by alarregoity-inflexsys** [comment]
Hello 

I think I have the same kind of problem with the attached pdf.
It uses embedded fonts.


Armand Larregoity
[fonts_tests2.pdf](https://github.com/katjas/PDFrenderer/files/70044/fonts_tests2.pdf)

**Comment by katjas** [comment]
Hi there,
I think this issue is fixed with the latest merging of bug fixes from Armand.
Kind regards,
Katja
