### ISSUE TITLE
Any chance you will support GeoPress pdfs?

### ISSUE THREAD

**Issue by lizlynch99** [katjas/PDFrenderer#32]
When I try and convert particular pdfs from GeoPress I get to "JPXDecode failed. No reader available".

Do you plan to support more pdf types? I can give you examples of the pdfs if anyone want them.

**Comment by Betazoid** [comment]
Seems that JPEG2000 support is not available. JPXDecode is a stream filter for JPEG2000 compressed data (usually images).

**Comment by Betazoid** [comment]
As the JPXDecode implementation uses Image I/O you might get the support if JAI (Java Advanced Imaging) is installed in your JVM environment.

**Comment by katjas** [comment]
Hi there,

Betazoid is right, the jpeg 2000 format is already supported - not in an own implementation but depending on an available reader which is loaded via ImageIO.
So if an appropriate library (e.g. JAI) is installed in your environment, it should work fine.

Kind regards,
Katja
