### ISSUE TITLE
File with multiple page sizes causes conversion error

### ISSUE THREAD

**Issue by porto2112** [katjas/PDFrenderer#37]
Hi,

I'm trying to convert a pdf file to jpeg using PDFRenderer. This operation works fine in most situations, but I'm facing the following error when I try to convert a pdf file which has multiple page formats:

com.sun.pdfview.PDFParseException: Expected number for first xref entry
        at com.sun.pdfview.PDFFile.readTrailer(Unknown Source)
        at com.sun.pdfview.PDFFile.parseFile(Unknown Source)
        at com.sun.pdfview.PDFFile.<init>(Unknown Source)
        at com.sun.pdfview.PDFFile.<init>(Unknown Source)

I'm not sure if the size of pages is causing that, but it seems to be the only different property comparing to the files I'm used to work with.

**Comment by katjas** [comment]
Hi there,
do you have an example PDF file for this? Otherwise it's hard to analyse the problem.
Thanks and kind regards,
Katja

**Comment by katjas** [comment]
No example received since nearly 2 years, so I'll close this case now.
