### ISSUE TITLE
Problem printing "quoteright" 

### ISSUE THREAD

**Issue by alarregoity-inflexsys** [katjas/PDFrenderer#42]
Hello

With the attached PDF, the quote in "l'E-Santé" is not displayed in the image.
[Tests_fonts3_armand.pdf](https://github.com/katjas/PDFrenderer/files/73382/Tests_fonts3_armand.pdf)

It shows:

![tests_fonts3_armand](https://cloud.githubusercontent.com/assets/16403476/12022530/dd364194-ad90-11e5-9e22-e098d3f40e78.jpg)

instead of 

![capture](https://cloud.githubusercontent.com/assets/16403476/12022555/219b291c-ad91-11e5-9668-e8a086ee8a7d.PNG)

**Comment by katjas** [comment]
Hello Armand,
thanks a lot for providing the patch, I have merged it now.
Kind regards,
Katja
