### ISSUE TITLE
Image not displayed

### ISSUE THREAD

**Issue by alarregoity-inflexsys** [katjas/PDFrenderer#44]
With the attached PDF 
[Test_background3.pdf](https://github.com/katjas/PDFrenderer/files/73426/Test_background3.pdf)

we get the following image

![test_background3](https://cloud.githubusercontent.com/assets/16403476/12023296/61906e72-ad98-11e5-909b-a2a25ca716b7.jpg)

instead of 

![capture](https://cloud.githubusercontent.com/assets/16403476/12023300/697e4ffa-ad98-11e5-82f5-64bbc4eb24e5.PNG)

There is no error in the console log.

Armand Larregoity

**Comment by katjas** [comment]
Hello Armand,
thanks a lot for providing the patch, I have merged it now.
Kind regards,
Katja
