### ISSUE TITLE
Trimbox vs CropBox

### ISSUE THREAD

**Issue by peetkes** [katjas/PDFrenderer#9]
When I process a PDF with crop marks, I see those crop marks in the images of the pages.
On http://www.prepressure.com/pdf/basics/page-boxes it is stated that one should always take the Trimbox whenever you need the actual size of the PDF. By default the TrimBox and CropBox are the same size, but in a PDF with crop marks they are not the same.
In the class PDFFile methode createPage, the MediaBox and the CropBoxe are used and the CropBox is stronger. Shouldn't this be the TrimBox instead?

**Comment by katjas** [comment]
Thanks for the input, I consider the trimbox now.

Kind regards,
Katja
